CPP_SOURCES = FileInput.cpp
CPP_HEADERS = ../../include/FileInterface.h ../../include/Data.h

all: fileinput-1

fileinput-1: $(CPP_SOURCES) $(CPP_HEADERS)
	g++ -o fileinput-1 $(CPP_SOURCES)

clean:
	rm fileinput-1